# Site settings
site: ßUG5Y - Writeups
title: ßUG5Y - Writeups
keywords: ßUG5Y, Writeups, CTF, blog
description: ßUG5Y - Writeups
lang: en-US
timezone:  America/New_York
repo: # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: ßUG5Y - Writeups
  picture: assets/images/hackalotl.png 
  github: BUG5Y # github username
  linkedin: zachary-reed-0035b21a6 # linkedin username
  email: your-email@email.com # email adress


# URL settings
url: "https://BUG5Y.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
